name: tvm-build

# The conda channels to lookup the dependencies
channels:
  - conda-forge
  - anaconda

# The packages to install to the environment
dependencies:
  - python=3.8 # or 3.8. See https://github.com/apache/tvm/issues/8577 for more details on >= 3.9
  - conda-build
# - git
  - llvmdev=17.0.6 # llvmdev=18 can't compile TVM.
# - clangxx # windows visual studio already equipped with Clang
  - numpy
  - pytest
  - cython
  - cmake
  - bzip2
  - make
  - zlib
